export const SEARCH_VIDEO = 'SEARCH_VIDEO';
export const SEARCH_ON_API_VIDEO = 'SEARCH_ON_API_VIDEO';
export const IS_LOADING = 'IS_LOADING';
export const CLOSE_VIDEO_PLAYER = 'CLOSE_VIDEO_PLAYER';
export const OPEN_VIDEO_PLAYER = 'OPEN_VIDEO_PLAYER';
